"""
train_anyanwu_svm.py
==============================================================
Train the Anyanwu [16] RBF-SVM (C=1000, gamma='scale') and
export the fitted model as a pure-C++ header file that can be
#include'd directly into routing.cc — no external ML library
needed at simulation runtime.

Usage (from the scratch/ directory on the NS-3 host):
    python3 train_anyanwu_svm.py

Output:
    anyanwu_svm_model.h   <-- copy to same directory as routing.cc

Feature vector (8-D) — must match the C++ extractor in routing.cc:
    [0] flow_duration    (s)        time from first to current packet
    [1] packet_count     (pkts)     cumulative pkts seen for this node
    [2] byte_count       (bytes)    pkt_count * flow_packet_size
    [3] packet_rate      (pkt/s)    pkt_count / flow_duration
    [4] byte_rate        (B/s)      byte_count / flow_duration
    [5] flowmod_count    (events)   FlowMod/FAKE_BEACON/WRONG_FM events
    [6] flowmod_ratio               flowmod_count / max(pkt_count,1)
    [7] table_miss_rate             edcf_fm_cnt / max(edcf_bcn_total,1)

Hyperparameters (Anyanwu et al., GSCV result):
    C=1000, gamma='scale'
==============================================================
"""

import numpy as np
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

# ──────────────────────────────────────────────────────────────
# SECTION A: TRAINING DATA
# ──────────────────────────────────────────────────────────────
# Replace this section with your real dataset if available.
# Example with a CSV:
#   import pandas as pd
#   df = pd.read_csv("cic_ids_flows.csv")
#   X = df[["flow_duration","packet_count","byte_count",
#            "packet_rate","byte_rate","flowmod_count",
#            "flowmod_ratio","table_miss_rate"]].values
#   y = df["label"].values   # 0=benign, 1=attack
# ──────────────────────────────────────────────────────────────
np.random.seed(42)
N = 3000  # samples per class

# BENIGN flows: normal SDVN control traffic
benign = np.column_stack([
    np.random.uniform(0.5, 240, N),                # flow_duration
    np.random.randint(1, 80, N).astype(float),      # packet_count
    np.random.uniform(100, 8000, N),               # byte_count
    np.random.uniform(0.05, 6.0, N),               # packet_rate
    np.random.uniform(5, 600, N),                  # byte_rate
    np.random.randint(0, 4, N).astype(float),       # flowmod_count
    np.random.uniform(0.0, 0.12, N),               # flowmod_ratio
    np.random.uniform(0.0, 0.08, N),               # table_miss_rate
])

# ATTACK flows: DDoS / control-plane flooding
attack = np.column_stack([
    np.random.uniform(0.01, 15.0, N),              # flow_duration (short bursts)
    np.random.randint(300, 3000, N).astype(float),  # packet_count (high)
    np.random.uniform(30000, 300000, N),            # byte_count (high)
    np.random.uniform(30.0, 600.0, N),              # packet_rate (very high)
    np.random.uniform(3000, 60000, N),              # byte_rate (very high)
    np.random.randint(20, 300, N).astype(float),    # flowmod_count (high)
    np.random.uniform(0.5, 1.0, N),                # flowmod_ratio (high)
    np.random.uniform(0.35, 1.0, N),               # table_miss_rate (high)
])

X = np.vstack([benign, attack])
y = np.array([0] * N + [1] * N)  # 0=benign, 1=attack

print(f"Dataset: {X.shape[0]} samples, {X.shape[1]} features")
print(f"Class balance: {np.sum(y==0)} benign, {np.sum(y==1)} attack")

# ──────────────────────────────────────────────────────────────
# SECTION B: TRAIN THE MODEL
# Exact hyperparameters from Anyanwu et al. (GSCV result):
#   C=1000, kernel='rbf', gamma='scale'
# ──────────────────────────────────────────────────────────────
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

svm = SVC(kernel='rbf', C=1000, gamma='scale', decision_function_shape='ovr')
svm.fit(X_scaled, y)

# gamma='scale' resolves to: 1 / (n_features * X.var())
# Access the resolved numeric value via svm._gamma
gamma_val = svm._gamma
n_sv = svm.support_vectors_.shape[0]
n_f  = svm.support_vectors_.shape[1]

print(f"\nTraining complete:")
print(f"  Support vectors : {n_sv}")
print(f"  gamma (scale)   : {gamma_val:.10f}")
print(f"  Intercept b     : {svm.intercept_[0]:.10f}")

# Quick accuracy check on training set
y_pred = svm.predict(X_scaled)
acc = np.mean(y_pred == y)
print(f"  Training acc    : {acc*100:.1f}%")

# ──────────────────────────────────────────────────────────────
# SECTION C: EXPORT TO C++ HEADER
# ──────────────────────────────────────────────────────────────
sv = svm.support_vectors_   # shape (n_sv, n_f)
dc = svm.dual_coef_[0]      # shape (n_sv,)  — αᵢ * yᵢ
b  = svm.intercept_[0]
mu    = scaler.mean_
sigma = scaler.scale_

out = []
out.append("// =================================================================")
out.append("// AUTO-GENERATED by train_anyanwu_svm.py  —  DO NOT EDIT MANUALLY")
out.append("// Anyanwu [16] RBF-SVM:  C=1000, gamma='scale'")
out.append(f"// Support vectors: {n_sv}, Features: {n_f}")
out.append("// =================================================================")
out.append("#pragma once")
out.append("#include <cmath>")
out.append("#include <cstdint>")
out.append("")

out.append(f"static const int    ANY_SVM_N_SV  = {n_sv};")
out.append(f"static const int    ANY_SVM_N_F   = {n_f};")
out.append(f"static const double ANY_SVM_GAMMA = {gamma_val:.17g};")
out.append(f"static const double ANY_SVM_B     = {b:.17g};")
out.append("")

# StandardScaler parameters
out.append("// StandardScaler: mean and std per feature")
out.append(f"static const double ANY_SVM_MU[{n_f}] = {{")
out.append("    " + ", ".join(f"{v:.17g}" for v in mu))
out.append("};")
out.append(f"static const double ANY_SVM_SIG[{n_f}] = {{")
out.append("    " + ", ".join(f"{v:.17g}" for v in sigma))
out.append("};")
out.append("")

# Dual coefficients αᵢ * yᵢ
out.append(f"// Dual coefficients (alpha_i * y_i), shape=({n_sv},)")
out.append(f"static const double ANY_SVM_DC[{n_sv}] = {{")
chunk_size = 4
dc_list = [f"{v:.17g}" for v in dc]
for i in range(0, len(dc_list), chunk_size):
    out.append("    " + ", ".join(dc_list[i:i+chunk_size]) + ",")
out[-1] = out[-1].rstrip(",")  # remove trailing comma on last line
out.append("};")
out.append("")

# Support vectors — stored row-major
out.append(f"// Support vectors, shape=({n_sv},{n_f})")
out.append(f"static const double ANY_SVM_SV[{n_sv}][{n_f}] = {{")
for row in sv:
    vals = ", ".join(f"{v:.17g}" for v in row)
    out.append(f"    {{{vals}}},")
out[-1] = out[-1].rstrip(",")
out.append("};")
out.append("")

# Inline predict function
out.append("""// -----------------------------------------------------------------
// any_svm_predict(x_raw)
//   x_raw : raw (unscaled) feature vector of length ANY_SVM_N_F
//   returns +1 (attack) or -1 (benign)
//
// Implements:
//   x_scaled[j] = (x_raw[j] - mu[j]) / sigma[j]
//   f = SUM_i dc[i] * exp(-gamma * ||SV[i] - x_scaled||^2) + b
//   label = sign(f)
// -----------------------------------------------------------------
inline int any_svm_predict(const double x_raw[ANY_SVM_N_F])
{
    // Step 1: StandardScaler normalisation
    double x[ANY_SVM_N_F];
    for (int j = 0; j < ANY_SVM_N_F; ++j)
        x[j] = (x_raw[j] - ANY_SVM_MU[j]) / ANY_SVM_SIG[j];

    // Step 2: RBF-SVM decision function
    //   f = Σᵢ dcᵢ · exp(−γ · ||SVᵢ − x||²) + b
    double f = ANY_SVM_B;
    for (int i = 0; i < ANY_SVM_N_SV; ++i) {
        double dist2 = 0.0;
        for (int j = 0; j < ANY_SVM_N_F; ++j) {
            double d = ANY_SVM_SV[i][j] - x[j];
            dist2 += d * d;
        }
        f += ANY_SVM_DC[i] * std::exp(-ANY_SVM_GAMMA * dist2);
    }

    // Step 3: sign of decision value
    return (f >= 0.0) ? 1 : -1;   // +1 = attack, -1 = benign
}
""")

header_text = "\n".join(out)
output_path = "anyanwu_svm_model.h"

with open(output_path, "w", encoding="utf-8") as fh:
    fh.write(header_text)

print(f"\nExported: {output_path}")
print(f"  Lines written: {len(out)}")
print("Copy this file to your NS-3 scratch directory alongside routing.cc")
