# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
import os
import os.path
import ns3waf
import sys

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    for filename in os.listdir(bld.path.abspath()):
        if filename[-3:] == '.cc':
            name = filename[:-3]
            obj = bld.create_ns3_program(name, all_modules)
            obj.source = filename
            obj.lib = ['pbc', 'gmpxx', 'gmp', 'crypto', 'oqs']
            obj.libpath  = ['/home/kumesha/liboqs-install/lib']
            obj.rpath    = ['/home/kumesha/liboqs-install/lib']

    for filename in os.listdir(bld.path.abspath()):
        if os.path.isdir(os.path.join(bld.path.abspath(), filename)):
            if filename != '.svn':
                bld.recurse(filename)
