// ============================================================================
//  edcf_lkh.h  —  Logical Key Hierarchy (LKH) for O(log n) group rekeying
// ----------------------------------------------------------------------------
//  Implements Eq 3.45-3.50 of the methodology (Section 3.5.1, "Group Key
//  Management via Logical Key Hierarchy"). Wraps every tree-node key using
//  the AES-256-GCM primitive already implemented in edcf_crypto.h
//  (previously defined but never called anywhere in routing.cc — this
//  module is its first real caller).
//
//    K_i        = { k_u : u in path(leaf_i, root) }              (Eq 3.45)
//    Join_Msg_i = { Enc_{k_sib(u)}(k_u) : u in path(leaf_i, root) }  (Eq 3.47)
//    Rekey_Msg  = { Enc_{k_sib(u)}(k'_u) : u in path(leaf_i, root), u != root }
//               U { Enc_{k_leftchild}(k'_root), Enc_{k_rightchild}(k'_root) }
//                                                                   (Eq 3.48)
//    |Rekey_Msg| = O(log n), within the report's stated 2*ceil(log2 n)
//                  bound (Eq 3.49): (depth - 1) sibling-wrapped ancestor
//                  entries plus exactly 2 extra entries for the new root
//                  key (one wrapped under each of the root's two children,
//                  so EVERY remaining member -- on either top-level
//                  subtree, not just the isolated leaf's own side -- can
//                  recover k'_root from whichever of the two it can
//                  decrypt). This matches the report's stated coefficient
//                  of "2" in 2*ceil(log2 n) exactly when the isolated
//                  leaf's ancestor chain has depth-1 sibling-wrapped
//                  entries plus these 2 root entries.
//    gsk'_j = KDF(k'_root || id_j)  for all j in V \ I            (Eq 3.50)
//
//  Tree is a complete binary tree over n leaves (one per current group
//  member, i.e. vehicle). Internal node keys are random AES-256 keys
//  generated by the RSU acting as Group Manager (GM); this is the SAME
//  RSU role already used for FALCON RSU keys and the Paillier/group-sig
//  group manager, consistent with Section 3.5.1.
// ============================================================================
#ifndef EDCF_LKH_H
#define EDCF_LKH_H

#include "edcf_crypto.h"
#include <vector>
#include <unordered_map>
#include <cmath>
#include <stdexcept>

namespace edcf {
namespace lkh {

// ---------------------------------------------------------------------------
//  Tree node indexing: standard array-heap layout. Node 0 = root.
//  Node u's children are 2u+1, 2u+2; node u's parent is (u-1)/2.
//  Node u's sibling is u-1 if u is odd-positioned... we use the standard
//  "sibling = u XOR 1 relative to parent's children" rule below.
// ---------------------------------------------------------------------------
struct LkhTree {
    int n_leaves = 0;                 // current group size (vehicles)
    int depth    = 0;                 // ceil(log2(n_leaves))
    int n_nodes  = 0;                 // total tree nodes (complete binary tree, 2*leaves-1 ideal case)
    std::unordered_map<int, Bytes> node_key;   // node index -> 32-byte AES key k_u
    std::unordered_map<int, int>   leaf_of_member;  // member id -> leaf node index
};

inline int parent_of(int u) { return (u - 1) / 2; }
inline int sibling_of(int u) {
    if (u == 0) throw std::runtime_error("lkh: root has no sibling");
    return (u % 2 == 1) ? (u + 1) : (u - 1);   // odd index = left child, sibling is u+1
}
inline int left_child(int u)  { return 2*u + 1; }
inline int right_child(int u) { return 2*u + 2; }

// Path from a leaf up to (and including) the root: {leaf, parent, ..., root}.
inline std::vector<int> path_to_root(int leaf) {
    std::vector<int> p;
    int u = leaf;
    p.push_back(u);
    while (u != 0) { u = parent_of(u); p.push_back(u); }
    return p;
}

// ---------------------------------------------------------------------------
//  Build the initial tree for n group members. Generates a fresh random
//  AES-256 key for every internal/leaf node, including the root k_root
//  used downstream as the DKG-derived master secret's LKH-side counterpart
//  (the report treats k_root as flowing FROM DKG into LKH — see
//  edcf_dkg.h::dkg_reconstruct_kroot for the DKG side; this module's
//  k_root is initialised FROM that reconstructed value when available, or
//  freshly random for a standalone LKH-only test/demo).
// ---------------------------------------------------------------------------
inline LkhTree build_tree(int n_members, const Bytes* seed_kroot = nullptr) {
    LkhTree t;
    t.n_leaves = n_members;
    t.depth    = (n_members <= 1) ? 0 : (int)std::ceil(std::log2((double)n_members));
    // Complete binary tree sized for n_members leaves at the bottom level.
    t.n_nodes  = 2 * n_members - 1;
    if (t.n_nodes < 1) t.n_nodes = 1;

    for (int u = 0; u < t.n_nodes; ++u) {
        if (u == 0 && seed_kroot != nullptr) {
            Bytes k = *seed_kroot;
            k.resize(AES_KEY_LEN, 0);
            t.node_key[u] = k;
        } else {
            t.node_key[u] = random_bytes(AES_KEY_LEN);
        }
    }
    // Leaves occupy the LAST n_members indices of this array-heap layout.
    int first_leaf = t.n_nodes - n_members;
    for (int i = 0; i < n_members; ++i)
        t.leaf_of_member[i] = first_leaf + i;
    return t;
}

// ---------------------------------------------------------------------------
//  Key set K_i a member holds: every key along its leaf-to-root path
//  (Eq 3.45). Returned as (node_index, key) pairs for clarity/logging.
// ---------------------------------------------------------------------------
inline std::vector<std::pair<int, Bytes>> member_key_set(const LkhTree& t, int member_id) {
    auto it = t.leaf_of_member.find(member_id);
    if (it == t.leaf_of_member.end())
        throw std::runtime_error("lkh: unknown member");
    std::vector<std::pair<int, Bytes>> ks;
    for (int u : path_to_root(it->second))
        ks.push_back({u, t.node_key.at(u)});
    return ks;
}

// ---------------------------------------------------------------------------
//  Join_Msg_i (Eq 3.47): for each node u on the new member's path, encrypt
//  k_u under k_sib(u) (the sibling subtree's key) using REAL AES-256-GCM
//  (edcf_crypto.h::aes256_gcm_wrap). Existing members holding k_sib(u) can
//  decrypt and learn k_u without ever seeing the new member's leaf secret.
// ---------------------------------------------------------------------------
struct WrappedEntry { int node; int encrypted_under_sibling_of; Bytes wrapped; };

inline std::vector<WrappedEntry> join_message(const LkhTree& t, int new_member_id) {
    std::vector<WrappedEntry> msg;
    for (auto& [u, ku] : member_key_set(t, new_member_id)) {
        if (u == 0) continue;          // root has no sibling to encrypt under for the join step itself
        int sib = sibling_of(u);
        const Bytes& k_sib = t.node_key.at(sib);
        Bytes wrapped = aes256_gcm_wrap(k_sib, ku);
        msg.push_back({u, sib, wrapped});
    }
    return msg;
}

// ---------------------------------------------------------------------------
//  Leave/isolation rekeying (Eq 3.48): when member i is isolated, every key
//  on path(leaf_i, root) is refreshed. Returns the new keyed tree AND the
//  Rekey_Msg broadcast list. |Rekey_Msg| = 2*ceil(log2 n) per Eq 3.49 —
//  verified by the test harness below.
// ---------------------------------------------------------------------------
inline std::vector<WrappedEntry> rekey_on_isolation(LkhTree& t, int isolated_member_id) {
    auto it = t.leaf_of_member.find(isolated_member_id);
    if (it == t.leaf_of_member.end())
        throw std::runtime_error("lkh: unknown member");
    std::vector<int> path = path_to_root(it->second);   // includes the isolated leaf itself

    // Fresh keys for every node STRICTLY ABOVE the isolated leaf (the leaf
    // key itself is simply discarded -- the isolated member no longer needs
    // any key). We still must inform every node on the path's *ancestors*
    // and re-wrap each new ancestor key under its (old, still-valid)
    // sibling key so non-isolated members can pick it up.
    std::vector<WrappedEntry> rekey_msg;
    for (size_t idx = 1; idx < path.size(); ++idx) {     // skip the isolated leaf itself
        int u = path[idx];
        if (u == 0) continue;                             // root handled separately below
        Bytes new_key = random_bytes(AES_KEY_LEN);
        int sib = sibling_of(u);
        const Bytes& k_sib_old = t.node_key.at(sib);      // sibling subtree's key is unaffected by this isolation
        Bytes wrapped = aes256_gcm_wrap(k_sib_old, new_key);
        rekey_msg.push_back({u, sib, wrapped});
        t.node_key[u] = new_key;                          // commit the refreshed key
    }

    // Root handling: k_root must change (the isolated member's old credentials
    // must not derive valid future gsk' values), but the root has no sibling
    // to wrap a single fresh key under. Instead, broadcast the new root key
    // wrapped under EACH of the root's two children's CURRENT keys (one of
    // which was just refreshed above if it lies on the isolated path; the
    // other is untouched). Every remaining member holds at least one of
    // these two child keys (every leaf's path passes through exactly one
    // root-child), so every remaining member can recover k'_root from
    // whichever of the two wrapped copies it can decrypt -- preserving the
    // "decrypt at least one ciphertext to stay current" property network-
    // wide, not just within the isolated leaf's own subtree.
    if (t.n_nodes > 1) {
        Bytes new_root_key = random_bytes(AES_KEY_LEN);
        int lc = left_child(0), rc = right_child(0);
        if (t.node_key.count(lc)) {
            Bytes wrapped_l = aes256_gcm_wrap(t.node_key.at(lc), new_root_key);
            rekey_msg.push_back({0, lc, wrapped_l});
        }
        if (t.node_key.count(rc)) {
            Bytes wrapped_r = aes256_gcm_wrap(t.node_key.at(rc), new_root_key);
            rekey_msg.push_back({0, rc, wrapped_r});
        }
        t.node_key[0] = new_root_key;
    }
    // Remove the isolated member's leaf mapping entirely.
    t.leaf_of_member.erase(isolated_member_id);
    return rekey_msg;
}

// ---------------------------------------------------------------------------
//  A remaining member processes a Rekey_Msg: decrypt every entry it CAN
//  decrypt (it holds the sibling key for exactly the entries on its own
//  path), updating its local view of the tree. Demonstrates that "each
//  remaining member needs to decrypt exactly one ciphertext to stay
//  current" per the report's Eq 3.48 commentary.
// ---------------------------------------------------------------------------
inline int apply_rekey_as_member(LkhTree& member_view, int member_id,
                                  const std::vector<WrappedEntry>& rekey_msg) {
    auto path = path_to_root(member_view.leaf_of_member.at(member_id));
    int decrypted_count = 0;
    for (auto& entry : rekey_msg) {
        // This member can decrypt `entry` iff it already holds the key of
        // node `entry.encrypted_under_sibling_of` (i.e. that node lies on
        // its own path -- meaning entry.node is its sibling-of-ancestor).
        bool holds_sibling_key = (member_view.node_key.find(entry.encrypted_under_sibling_of)
                                   != member_view.node_key.end());
        if (!holds_sibling_key) continue;
        Bytes out;
        if (aes256_gcm_unwrap(member_view.node_key.at(entry.encrypted_under_sibling_of),
                               entry.wrapped, out)) {
            member_view.node_key[entry.node] = out;
            ++decrypted_count;
        }
    }
    return decrypted_count;
}

// ---------------------------------------------------------------------------
//  Updated group signing key after rekeying (Eq 3.50):
//    gsk'_j = KDF(k'_root || id_j)   for all j in V \ I
//  Reuses HKDF-SHA-512 from edcf_crypto.h with domain label "LKH-GSK" to
//  stay independent of the HMAC group key derived under "HMAC-AUTH"
//  (edcf_crypto.h::derive_group_key), exactly as Eq 3.22's commentary
//  requires.
// ---------------------------------------------------------------------------
inline Bytes derive_updated_gsk(const Bytes& new_kroot, int member_id) {
    static const std::string LABEL = "EDCF-LKH-GSK";
    Bytes info = to_bytes(LABEL);
    Bytes id_bytes = to_bytes(std::to_string(member_id));
    info.insert(info.end(), id_bytes.begin(), id_bytes.end());
    return hkdf_sha512(new_kroot, /*salt=*/{}, info, 32);
}

} // namespace lkh
} // namespace edcf
#endif // EDCF_LKH_H
